/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComposeEditor: typeof import('./src/components/ComposeEditor.vue')['default']
    ComposeToolbar: typeof import('./src/components/ComposeToolbar.vue')['default']
    ConfigEditor: typeof import('./src/components/ConfigEditor.vue')['default']
    ConfigMountEditor: typeof import('./src/components/ConfigMountEditor.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    LinuxCapabilitiesToggle: typeof import('./src/components/LinuxCapabilitiesToggle.vue')['default']
    NetworkEditor: typeof import('./src/components/NetworkEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecretEditor: typeof import('./src/components/SecretEditor.vue')['default']
    SecretMountEditor: typeof import('./src/components/SecretMountEditor.vue')['default']
    SectionBox: typeof import('./src/components/SectionBox.vue')['default']
    ServiceBlobsEditor: typeof import('./src/components/ServiceBlobsEditor.vue')['default']
    ServiceBuildEditor: typeof import('./src/components/ServiceBuildEditor.vue')['default']
    ServiceCapabilitiesEditor: typeof import('./src/components/ServiceCapabilitiesEditor.vue')['default']
    ServiceConfigsList: typeof import('./src/components/ServiceConfigsList.vue')['default']
    ServiceDependsOnList: typeof import('./src/components/ServiceDependsOnList.vue')['default']
    ServiceDeployEditor: typeof import('./src/components/ServiceDeployEditor.vue')['default']
    ServiceDevicesList: typeof import('./src/components/ServiceDevicesList.vue')['default']
    ServiceDnsList: typeof import('./src/components/ServiceDnsList.vue')['default']
    ServiceEditor: typeof import('./src/components/ServiceEditor.vue')['default']
    ServiceEnvironmentEditor: typeof import('./src/components/ServiceEnvironmentEditor.vue')['default']
    ServiceHealthcheckEditor: typeof import('./src/components/ServiceHealthcheckEditor.vue')['default']
    ServiceImageEditor: typeof import('./src/components/ServiceImageEditor.vue')['default']
    ServiceLabelsEditor: typeof import('./src/components/ServiceLabelsEditor.vue')['default']
    ServiceLoggingEditor: typeof import('./src/components/ServiceLoggingEditor.vue')['default']
    ServiceNetworkModeEditor: typeof import('./src/components/ServiceNetworkModeEditor.vue')['default']
    ServiceNetworksList: typeof import('./src/components/ServiceNetworksList.vue')['default']
    ServicePortsDualEditor: typeof import('./src/components/ServicePortsDualEditor.vue')['default']
    ServicePortsList: typeof import('./src/components/ServicePortsList.vue')['default']
    ServiceSecretsList: typeof import('./src/components/ServiceSecretsList.vue')['default']
    ServiceSecurityOptList: typeof import('./src/components/ServiceSecurityOptList.vue')['default']
    ServiceSidebar: typeof import('./src/components/ServiceSidebar.vue')['default']
    ServiceSysctlsEditor: typeof import('./src/components/ServiceSysctlsEditor.vue')['default']
    ServiceVolumesList: typeof import('./src/components/ServiceVolumesList.vue')['default']
    ValidationSummaryPanel: typeof import('./src/components/ValidationSummaryPanel.vue')['default']
    VolumeEditor: typeof import('./src/components/VolumeEditor.vue')['default']
    VolumeMountEditor: typeof import('./src/components/VolumeMountEditor.vue')['default']
  }
}
